# Generated by Django 4.1 on 2022-09-17 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ANSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enterprise', models.BooleanField(blank=True, default=False)),
                ('enterprise_name', models.CharField(blank=True, default='', max_length=256)),
                ('is_home_owner', models.BooleanField(blank=True, default=False)),
                ('user_uid', models.CharField(blank=True, max_length=256, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=256)),
                ('blocked_enterprises', models.ManyToManyField(blank=True, related_name='block_enterprise', to=settings.AUTH_USER_MODEL)),
                ('pending_enterprises', models.ManyToManyField(blank=True, related_name='pending_enterprise', to=settings.AUTH_USER_MODEL)),
                ('trusted_enterprises', models.ManyToManyField(blank=True, related_name='trust_enterprise', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
